"""detect_changes

Revision ID: 221120ca61a5
Revises: 
Create Date: 2025-04-30 16:00:34.716436-04:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '221120ca61a5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('estado_plan')
    op.drop_table('plan_rutina_usuario')
    op.drop_table('habitos_diarios')
    op.drop_table('estado_meta')
    op.drop_table('estados_plan')
    op.drop_table('equipamiento_disponible')
    op.drop_table('preferencias_alimentarias')
    op.drop_table('seguimiento_rutina')
    op.drop_table('restricciones_usuario')
    op.drop_table('historial_medico')
    op.drop_table('estados_rutina')
    op.drop_table('tipos_objetivo')
    op.drop_index('correo', table_name='usuario')
    op.drop_table('usuario')
    op.drop_table('progreso_usuario')
    op.drop_table('condicion_fisica')
    op.drop_table('plan_dieta_usuario')
    op.drop_table('perfil_usuario')
    op.drop_table('tipo_objetivo')
    op.drop_table('estados_meta')
    op.drop_table('tipo_usuario')
    op.drop_table('alimentos_evitados')
    op.drop_table('tipos_usuario')
    op.drop_table('meta_usuario')
    op.drop_table('estado_rutina')
    op.drop_table('seguimiento_meta')
    op.drop_table('perfil_restriccion')
    op.drop_table('restriccion_usuario')
    op.drop_table('seguimiento_dieta')
    op.drop_table('ejercicio_preferido')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ejercicio_preferido',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_perfil', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tipo', mysql.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_perfil'], ['perfil_usuario.id'], name='ejercicio_preferido_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('seguimiento_dieta',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_plan_dieta', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha', sa.DATE(), nullable=True),
    sa.Column('descripcion', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['id_plan_dieta'], ['plan_dieta_usuario.id'], name='seguimiento_dieta_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('restriccion_usuario',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('descripcion', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('perfil_restriccion',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_perfil', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_restriccion', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_perfil'], ['perfil_usuario.id'], name='perfil_restriccion_ibfk_1'),
    sa.ForeignKeyConstraint(['id_restriccion'], ['restriccion_usuario.id'], name='perfil_restriccion_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('seguimiento_meta',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_meta_usuario', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha', sa.DATE(), nullable=True),
    sa.Column('avance', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['id_meta_usuario'], ['meta_usuario.id'], name='seguimiento_meta_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('estado_rutina',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('descripcion', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('meta_usuario',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_tipo_objetivo', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_tipo_objetivo'], ['tipo_objetivo.id'], name='meta_usuario_ibfk_2'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], name='meta_usuario_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tipos_usuario',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('descripcion', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('alimentos_evitados',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_perfil', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('descripcion', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['id_perfil'], ['perfil_usuario.id'], name='alimentos_evitados_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tipo_usuario',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('descripcion', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('estados_meta',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('descripcion', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tipo_objetivo',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('descripcion', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('perfil_usuario',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('genero', mysql.ENUM('masculino', 'femenino', 'otro', 'prefiero_no_decir'), nullable=True),
    sa.Column('edad', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('peso', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('altura', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('nivel_actividad', mysql.ENUM('sedentario', 'moderado', 'activo', 'muy_activo', 'extremo'), nullable=True),
    sa.Column('objetivo_principal', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('tiempo_meta', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('nivel_compromiso', mysql.TINYINT(), autoincrement=False, nullable=True),
    sa.Column('id_usuario', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], name='perfil_usuario_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('plan_dieta_usuario',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_estado_plan', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_estado_plan'], ['estado_plan.id'], name='plan_dieta_usuario_ibfk_2'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], name='plan_dieta_usuario_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('condicion_fisica',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_perfil', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('frecuencia_ejercicio', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('tiempo_disponible', mysql.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_perfil'], ['perfil_usuario.id'], name='condicion_fisica_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('progreso_usuario',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('descripcion', mysql.TEXT(), nullable=True),
    sa.Column('fecha', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], name='progreso_usuario_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('usuario',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('correo', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('contraseña', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('estado', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('id_tipo_usuario', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_tipo_usuario'], ['tipo_usuario.id'], name='usuario_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('correo', 'usuario', ['correo'], unique=True)
    op.create_table('tipos_objetivo',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('descripcion', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('estados_rutina',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('descripcion', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('historial_medico',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_perfil', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('condicion_cronica', mysql.TEXT(), nullable=True),
    sa.Column('medicamentos', mysql.TEXT(), nullable=True),
    sa.Column('lesiones', mysql.TEXT(), nullable=True),
    sa.Column('antecedentes_familiares', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['id_perfil'], ['perfil_usuario.id'], name='historial_medico_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('restricciones_usuario',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('descripcion', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('seguimiento_rutina',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_plan_rutina', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha', sa.DATE(), nullable=True),
    sa.Column('comentarios', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['id_plan_rutina'], ['plan_rutina_usuario.id'], name='seguimiento_rutina_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('preferencias_alimentarias',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_perfil', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tipo', mysql.ENUM('dieta', 'alergia', 'favorito'), nullable=True),
    sa.Column('valor', mysql.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id_perfil'], ['perfil_usuario.id'], name='preferencias_alimentarias_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('equipamiento_disponible',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_perfil', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('equipo', mysql.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_perfil'], ['perfil_usuario.id'], name='equipamiento_disponible_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('estados_plan',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('descripcion', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('estado_meta',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('descripcion', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('habitos_diarios',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_perfil', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('horas_sueno', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('calidad_sueno', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('nivel_estres', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('agua_dia', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('comidas_dia', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('habitos_snack', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('horas_pantalla', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('tipo_trabajo', mysql.VARCHAR(length=30), nullable=True),
    sa.ForeignKeyConstraint(['id_perfil'], ['perfil_usuario.id'], name='habitos_diarios_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('plan_rutina_usuario',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_estado_plan', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], name='plan_rutina_usuario_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('estado_plan',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('descripcion', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ### 